sudo: false

language: c

env:
  global:
    - AWS_BUCKET: dzhus.org
    - AWS_DEFAULT_REGION: eu-west-2
    - SITEMAP_LOCATION: http://dzhus.org/sitemap.xml
    # AWS access keys
    - secure: "MSmfVoFTvDr+/SSyt8FOl8bfTVwQavkVHGnB92daEVGNhyJdhHr3ycKhGmG6bgcGl4kayohpkj8/nYv74LKoacNz+jAjoA6kQHWg8aL5C1X+5S44uSwL6JRNbav9afRSLDfZ9waScvphusrv6sunWI5DvGmY0d1Ra4sfpjChfbHv+X1vqNmKRsh2y2pZUf64CbASeQqr9Uy8vlcLHQKpoigIUEKIGPzqVLVcyRXEgXbBrpI4bXHz5i5vXPWExkGnwqtX7pkkgHmSoVhchgV4DaUFxrz4NIjOd7ajIYbLIqrCzNvq9fjxc8lgJgQ6sh84sgQXpyMLGwNGaztIlMVAJxiMIuSCPnyeU5rbvm1owR/SsOMaOLrscwPIYJsIpScYzG1AcAki5RX7AFpYwm2n3NEb2FHZoVa0yFeKWzA5XM1tpcRBybn9Bm+4TOvxNi9E5UywzAbDyVeH5ipFM/kVXWpz9yoz3u4jRq2aal4shR+XpwXlNXWTuXqz8M15jUk+EpNhMqcHIkMkDaAED/qNfhd5dTKbUJi2PG7kiHInms+rzKl2eB7AGQEptAOqsr2V9izAppBHOVVz/Dfz+TBsJdVCQZhuZ6Td3NqjKQV4ypxxlHt6EuQaUFMQ7cf+CnywZVsULTNYRZT35CFu9dGwXmCUmC3mr0ZImg1WKvLHz84="
    - secure: "s4QFNAVBllInCIzp55r5wkpBwXf9ySYmOYRMEum06RihviHbzZi4GaPGS/fw+3iOiqvONvyQ63hoVtW6aO39xE9BrcCTpMjnnYSlO4Y/xRMLUvAnpyLS9IVf4nJsU+84SFTklavnus2PXL20rZgYG2f393/JXMaTGFd4XmKEIbZhlk9RyX3yqKAPjfyaktlhVhlx1VyPeGq6zA2Bj5UsuxJwyM1fCzpoP2aEweHBG1rIRwjSnNYBTLjiX69AJjjugqCAyAxc0y6OA40v+OVml7ljWrArcQ5dugHR0EUAAhoEs8I7ZFWHEnobIr1HBFWaJJprFThe/oo8BJ9SI492UCzj7QOTEzX1i9AzFlX8hQ9f1MGqkjq4PkIwwPUb0m8Ue9WRrrWh85sU+9YTJ0tet0p3U5y0FBB490JsXIju8LMzv1u/g64i4MgoJvbhhJGQZwANlFnanwR7+SpXlcY7tdC90RwDOtNnAsq1epaqMAZGRCJr9iAu4fuzew3Hgf51mNoY/+ys5BTOvIbpW99at7q3QqdTQ8EXEHyG1nzbk4l4VqRybHrL/ID26t4USWtwJglNkGuDQcSXqkdoXThWzla/KDJo2OGjRk6RoTAVaHtUQGRnD8avFxrMTbWjobKHlYxcZ2xcAh2EFIvcpX/oVG70ZC6e/JMd/f+vnU/SoCc="
    # CloudFlare access keys
    - secure: "dnpy5uAG7D6uLZ0FCPpuqcnq1Mdw5HFemLRyJLFK4XcNCkTVWfMFSvWBSIpUt/lVKHR7bn4bVT9PckAaLGMX4WS8h+0G9s+bGsrCQ4ujOFUdB0CYkMHP+W2LGrAu2CIiPacttCtITSRXPdkN2nkShvq/E9wSB+QmM8b94epf9hdhQVMkC6Sn0lyU/PgnJbn4P/NLnkOslz4i/U1aCvfErEcSsSZ7ctm5Z9M3wsV4WHyx+9gv7ftBEDCAgblJrYuI6knv2dwQFkyAXse2K5KWCXczqoQpAYxjBYZcb6VpLIYj6CI9W2Bv4S5Qsom7c1bVRRxrcNXlt6mpna64dCnthILxSVTPCSAyhj68Jz/vitdpxXgLLO2w7EIUhVSfZE8RSwu3+4nbgKllxOgV9KvCC+jnCVixKQEUvqJKdoB95HBLRwhmQNvoP/T5vl+bNpYFdGDaGnIeiTiJQ+hQewBK+DxRVMuyEMd21X4fmHwfbkdiHmfjf8d4yK/GXQNjhT07GvRsdaVLIyiB46OGY2298BqlXoBIkp0gM7PG8N8wy0UkSo0UzFbWS3oITzcIVcd4nIxTXiLidi9ADJ70VcJmaViEjBhAgsnuV04Io5MWoIfuTZcUGynCRlXrMvmnlJJ0WC0mL0qlb07/Ss2nWvhpO7iwa+Pz5W4VUXnWvHwV8S0="
    - secure: "UON0lHW4aveFvmYS67NtaEU/zdQ/K8JRh3WSpf43yTI+PlCnLvHt8BU4ePOLUysHVD4QrVUAnspIH2Udef/fT5wzxIcMClkytbjiMaSgrrJ4xKMT47ttdWCkBeXW+L+eX95ih4Ljeiw3VdbtPetI3cYukpqTNvRqyKiVu2dG5vWh4idf7EqxW/9Gc7sdBUNtlPEheaiIGcf7uIGqtiPDxKwHGQL/hcoc8nKLmdQw/ofLuIX/EhzDnXpT/ZyVSWo54z50OJlprre4ewWP2T55mJKxLDWURMvh5gEeoYqmQBa7lIXV+bbLFPLADq9kLoc9eW/08AhD33bR97iA8CELLpGZQYsOGRXbvzjsBDaL7e5qtlJ45SdyMDsjkeB6Z8kETditxDh7Ok4veI4jIsaK1/VmjCZCpKqHrhiuVQ9gLgLT60qOrDl//gs5heWaMtZzElXHDsleQPuKKwgfGKbGULlbBJJxF5twQZNCqAa/pjjicjzckMENP+cYoFV8OusBcRSgrLxBQqTefrA9HLbPNnkjyhx/ABxwx2j4ivRG9wonJskoLjCfBCcJ2gmv0rL+FbKx8y0WhC4EPaOwLLIkZ5cJGiDaI8mWMSRNx9CB9/iyukRQVAkAVGM5RG7RnHauGL2XzEKhHLW8olpVEZ3nX939BIWLAfCLGzvtj2pqS9Y="
    - secure: "SrNr30BMUluuGBCuQNKmB/biC8UYTFyGu+eulX4iGKSliANpwyexLFWbTVSjwBqQv4PfQbtejKyEYPJ9oHQen/T40jtgc/2tHRfFwaMdyXf8LwXYBrHsZHVut++ok8msLxyzl5iEqKAIvz/2UQgkyp7LPQ8bUW22AcbbKDtGZ84c938SqFgUxfp6HXNq8YJPOKQIg2gtEJKCgn/HHBxOvAz1inwVjc/GEQiNYf2udyJVtZrn9lGYh4CcNb6Vl37X1ONYLBFQjX327Lb+9F6O/b5ZW/iG1BPL/je3z77jTxWcVpi8ZXXVAsE6HXUT4pDjFCoeXrQbOMz5Pzl7qxjQOS0IzA9BV8v9MR3ydPFJEeUYNg8OliGMrdUZGOcr4UxBhhB5Y3g1DXoFvBkmAhYDLgn7WX0uk1ZGAYWU6mc9mnVhxBsiiUkJTGHykukkGAoTylDJq7OLN3gHr2SKjJ35MdFMZCQMMBVKmWXn2SGcefOUQA/wZ5fLpNNCImyFmfHuGi07VmElZ45+Ahm/QfoNg/Qdf8pnR41k7v6URdmT7/8eMyBk/479wlioAxLmGT3jysirjO0WfJ4S5TYI+vcZNOW/aJ8FxjJa/Eo4NmLObtyrKaw1xN4gr8qgC402FwcDjOKyQRWWK241Pj4ViQyLQcz4+jdnKoC+DfVa2VwS5RI="

matrix:
  include:
    - env: FLAGS="" ARGS=""
      compiler: ": #stack default"
      addons: {apt: {packages: [libgmp-dev, python3-pip]}}

before_install:
- unset CC
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
- stack $ARGS --install-ghc --no-terminal build $FLAGS --pedantic --haddock --no-haddock-deps --test --bench
- stack exec site build

before_deploy:
  - python3 -m pip install --user awscli

deploy:
  provider: script
  script: aws s3 sync --delete _site s3://"$AWS_BUCKET"
  skip_cleanup: true
  on:
    branch: master

after_deploy:
- >
  curl -X POST
  "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache"
  -H "X-Auth-Email: $CLOUDFLARE_AUTH_EMAIL"
  -H "X-Auth-Key: $CLOUDFLARE_AUTH_KEY"
  -H "Content-Type: application/json"
  --data '{"purge_everything":true}'
- curl "http://google.com/ping?sitemap=$SITEMAP_LOCATION"

cache:
  directories:
  - .stack-work
  - _cache
  - _site
  - $HOME/.stack
