sudo: false

language: c

matrix:
  include:
    - env: FLAGS="" ARGS=""
      compiler: ": #stack default"
      addons: {apt: {packages: [libgmp-dev]}}

before_install:
- unset CC
- mkdir -p $HOME/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
- stack $ARGS --install-ghc --no-terminal build $FLAGS --pedantic --haddock --no-haddock-deps --test --bench
- stack exec site build

deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "dzhus-org"
  skip_cleanup: true
  local_dir: _site
  on:
    branch: master

cache:
  directories:
  - .stack-work
  - $HOME/.stack
