name:       dzhus-hakyll-blog
version:    0.1.0.0
license:    GPL-3
author:     Dmitry Dzhus
maintainer: dima@dzhus.org
copyright:  2017-2018 Dmitry Dzhus
github:     dzhus/blog

default-extensions:
  - DeriveGeneric
  - FlexibleContexts
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TypeFamilies

executables:
  site:
    main: site.hs
    ghc-options: -threaded
    dependencies:
      - base
      - classy-prelude
      - hakyll
      - pandoc
      - pandoc-types
      - pureMD5
      - skylighting
      - time
