name: Publish updates
on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_BUCKET: dzhus.org
  AWS_DEFAULT_REGION: eu-west-2
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
  SITEMAP_LOCATION: https://dzhus.org/sitemap.xml

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run:
          aws s3 sync --delete _site s3://"$AWS_BUCKET"

      - name: Purge CDN cache
        run: >-
          curl -X POST
          "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache"
          -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN"
          -H "Content-Type: application/json"
          --data '{"purge_everything":true}'
